### ISSUE TITLE
Bookmarks section is empty.

### ISSUE THREAD

**Issue by NeoMahler** [michalsukupcak/Material-New-Tab#2]
Hello,

Here you have a screenshot of my bookmarks section:
![Empty bookmarks](https://cloud.githubusercontent.com/assets/8308572/17269485/c35f0a8c-5649-11e6-9b6f-c3ba8c9dc5a8.png)

The extension has the permission "Read and write bookmarks" (Or something like that, I'm not using the English version of Chrome). I'm using the version    1.4.8 on elementary OS Freya

**Comment by michalsukupcak** [comment]
Hello Neo,

Sorry for the super long wait for a response. The extension has undertaken a significant revamp and this issue is no longer relevant.
